base_url = "codinginfinity.me"

title = "Coding Infinity"
description = "At infinity, nothing is impossible - just like in code"

default_language = "en"

highlight_code = true

# The theme to use for code highlighting.
# See below for list of allowed values.
highlight_theme = "dimmed-fluid"

generate_rss = true

taxonomies = [
    { name = "tags", paginate_by = 10 }
]

# The additional languages for the site.
# Example:
#     languages = [
#       {code = "fr", rss = true}, # there will be a RSS feed for French content
#       {code = "fr", search = true}, # there will be a Search Index for French content
#       {code = "it"}, # there won't be a RSS feed for Italian content
#     ]
#
languages = []

# When set to "true", the Sass files in the `sass` directory are compiled.
compile_sass = true

# When set to "true", a search index is built from the pages and section
# content for `default_language`.
build_search_index = false

# A list of glob patterns specifying asset files to ignore when the content
# directory is processed. Defaults to none, which means that all asset files are
# copied over to the `public` directory.
# Example:
#     ignored_content = ["*.{graphml,xlsx}", "temp.*"]
ignored_content = []

# A list of directories used to search for additional `.sublime-syntax` files.
extra_syntaxes = []

# Configuration of the link checker.
[link_checker]
skip_prefixes = [
    "http://old.fiolek.org",
    "http://old2.fiolek.org",
]

skip_anchor_prefixes = [
    "https://github.com/jakubfijalkowski/codinginfinity/blob/cafb0a0254e2b6a488cc703f83a74846e3187e0b/src/Sitemap.hs",
    "https://github.com/jakubfijalkowski/haskell-and-cpp/blob/master/Setup.hs",
    "https://github.com/projectkudu/kudu/wiki/REST-API"
]

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[extra]
author = "Jakub Fijałkowski"
copyright = "© Copyright 2016-2020, Jakub Fijałkowski"
twitter = "Fiolek_"
github = "jakubfijalkowski"
source = "https://github.com/jakubfijalkowski/codinginfinity"
